@startuml masterDevice_startup SD
'!include masterDevice_componentDiagram.iuml
!definelong sandr(master,slave,masterMsg,slaveMsg) 
master->slave : masterMsg
activate slave
slave->master : slaveMsg
deactivate slave
!enddefinelong
participant main as "main_statMod"
participant configMod as "configSystem_pacMod"
participant ifMod as "userIF_pacMod" 
participant streamMod as "streamParser_pacMod"
participant msgMod as "msgControl_pacMod"
participant visMod as "visualizer_pacMod"

main -> configMod : Engage Startup sequence
activate configMod
loop Start Modules
    sandr(configMod,ifMod,"Engage Startup Sequence","return IF info")
    sandr(configMod,streamMod,"Engage Startup Sequence","return if info")
    sandr(configMod,msgMod,"Engage Startup Sequence","return if info")
    sandr(configMod,visMod,"Engage Startup Sequence","return if info")
end
configMod -> main : Config Status
deactivate configMod



@enduml